# Source: dcgm-exporter/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-dcgm-exporter
  labels:
    app: nvidia-dcgm-exporter
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["nvidia-dcgm-exporter"]
  verbs: ["get"]
---
# Source: dcgm-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-dcgm-exporter
  labels:
    app: nvidia-dcgm-exporter
subjects:
- kind: ServiceAccount
  name: nvidia-dcgm-exporter
roleRef:
  kind: Role 
  name: nvidia-dcgm-exporter
  apiGroup: rbac.authorization.k8s.io
