{
 "title": "Kubernetes / Deployment / Overview",
 "description": "Kubernetes Deployment Overview",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "victoriametrics-datasource" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{cluster=\"$cluster\",namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment\",namespace=\"$namespace\",cluster=\"$cluster\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{cluster=\"$cluster\",deployment=\"$deployment\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_metadata_generation{cluster=\"$cluster\", deployment=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Create Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{cluster=\"$cluster\",deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "AVG CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "AVG Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"}) "
    }
   ]
  },
  {
   "title": "AVG Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"}[2m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", deployment=~\"$deployment\", __name__=\"kube_deployment_status_replicas_available\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "{namespace=~\"$namespace\", deployment=~\"$deployment\", __name__=\"kube_deployment_status_replicas_unavailable\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "{namespace=~\"$namespace\", deployment=~\"$deployment\", __name__=\"kube_deployment_status_replicas_updated\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Spec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", deployment=~\"$deployment\", __name__=\"kube_deployment_spec_replicas\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "{namespace=~\"$namespace\", deployment=~\"$deployment\", __name__=\"kube_deployment_spec_paused\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}