{
 "title": "GCP / CloudSQL",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {}
   },
   {
    "name": "database",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/up"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/memory/utilization"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }} ",
     "metricQuery": {
      "aliasBy": "{{ resource.label.database_id }} ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "resource.label.database_id" ],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/network/connections",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "nanovest",
      "query": "",
      "valueType": "INT64"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/network/connections"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    },
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/postgresql/num_backends"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/cpu/utilization"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Replica Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/mysql/replication/seconds_behind_master"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{ resource.label.database_id }}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.database_id",
       "=~",
       "$database",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/disk/utilization"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  }
 ]
}