{
 "title": "GCP / Redis",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {}
   },
   {
    "name": "instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Rejected Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "aliasBy": "{{resource.label.instance_id}}-{{metric.label.role}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.instance_id",
       "=~",
       "projects/stagingapplication/locations/europe-west1/instances/example-bl-redis",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/reject_connections_count"
      ],
      "groupBys": [
       "metric.label.role",
       "resource.label.instance_id"
      ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "aliasBy": "{{resource.label.instance_id}}-{{metric.label.role}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_COUNT",
      "filters": [
       "resource.label.instance_id",
       "=~",
       "$instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/server/uptime"
      ],
      "groupBys": [
       "metric.label.role",
       "resource.label.instance_id"
      ],
      "perSeriesAligner": "ALIGN_COUNT",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.instance_id}}-{{metric.label.role}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.instance_id",
       "=~",
       "$instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/memory/system_memory_usage_ratio"
      ],
      "groupBys": [
       "metric.label.role",
       "resource.label.instance_id"
      ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Redis Memory Usage High Threshold",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.instance_id}}-{{metric.label.role}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "resource.label.instance_id",
       "=~",
       "$instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/memory/system_memory_usage_ratio"
      ],
      "groupBys": [
       "metric.label.role",
       "resource.label.instance_id"
      ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  }
 ]
}