{
 "title": "K8s / Storage / PV",
 "description": "Dashboard of Kubernetes / OpenShift volume information at namespace level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "openshift",
  "k8s",
  "storage"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "victoriametrics-datasource" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   },
   {
    "name": "persistentvolumeclaim",
    "query": "label_values(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n count (\n   (kubelet_volume_stats_available_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"})\n   and\n   (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "PVC Stats",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": " (kube_persistentvolumeclaim_info { namespace = \"$namespace\",cluster=~\"$cluster\" })"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { namespace = \"$namespace\" ,cluster=~\"$cluster\"}) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\",cluster=~\"$cluster\" })) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { namespace = \"$namespace\",cluster=~\"$cluster\" }) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\",cluster=~\"$cluster\" })))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\",cluster=~\"$cluster\" })"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\",cluster=~\"$cluster\" })"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes { namespace = \"$namespace\" })"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\" })) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\" }))"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"})) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_unbound_pvc_count {exported_namespace = \"$namespace\",cluster=~\"$cluster\"}))) or (vector(0))"
    }
   ]
  },
  {
   "title": "Running PVCs % Used",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"})) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Use vs Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$persistentvolumeclaim",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "repeat": "persistentvolumeclaim",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\",cluster=~\"$cluster\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\",cluster=~\"$cluster\"}))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Use Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hourly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}[1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\",cluster=~\"$cluster\"}[1w])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  }
 ]
}